### ISSUE TITLE
Handle ERROR :Server going down

### ISSUE THREAD

**Issue by Nomarian** [mirrexagon/lua-irc-engine#20]
I'm running ngircd and after restarting the server, I noticed my loadavg spiked, the lua process was taking 100% CPU.

A temporary fix that I'm using now is

`
irc:set_callback("ERROR", function(self, one, two)
  self:QUIT(two[1])
  running = false
end)
`

IDK if a handler is better for this, it should timeout at least but it doesn't, I imagine because `while running do` is active? the script is basically the same as the example but with a big PRIVMSG callback.

-------

After some investigating on luasocket it seems you can catch a closed connection if you store the error, if error is "closed" then you should break or set running to false

`
while running do
 local line,err = client:receive()
 if line then
  irc:process(line)
 else
  if err=="closed" then running=false end
 end
end
`

perhaps irc:process should handle the error message internally?

**Comment by mirrexagon** [comment]
The intention was for `irc:process()` to be agnostic to how you are actually communicating with the network, so you could use LuaSocket, or you could something else that handled errors differently. So I think that the solution you came up with is what you should do.

The example should be updated to do what you did.\
`irc:process()` should probably also be changed to raise an error if `nil` is passed to it instead of just ignoring it (and the README updated as well), to reinforce that socket error handling should actually be done outside of `irc-engine`.

If you feel like raising an pull request to update those, please do! Otherwise I'll get around to it when I have time.

**Comment by Nomarian** [comment]
The problem is, nil is passed whenever a timeout happens. even worse if the connection is local. so I think its fine as is.

**Comment by mirrexagon** [comment]
I mean that handling timeouts should probably be done outside of `irc:process()`. In any case, there's not too much of a problem as is as you said, so that's fine. Thanks for the pull request!
